FROM swr.ap-southeast-3.myhuaweicloud.com/codearts-demo/ollama/ollama:0.6.3-01042025

# Install curl for health checks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Set and extract model name
ARG MODEL_URL="ollama://sailor2:1b"
RUN echo "${MODEL_URL#*//}" > /model_name.txt

# Preload the model
RUN /bin/sh -c ' \
    /bin/ollama serve & pid=$!; \
    for i in {1..30}; do \
        curl -s http://localhost:11434/api/tags > /dev/null && break; \
        sleep 1; \
    done; \
    /bin/ollama pull "$(cat /model_name.txt)"; \
    kill -15 $pid && wait $pid \
'
