apiVersion: v1 
kind: Service 
metadata: 
  annotations:   
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{
      "name":"elb-svc-openwebui",
      "type": "public",
      "bandwidth_name": "cce-bandwidth-kubeai",
      "bandwidth_chargemode": "traffic",
      "bandwidth_size": 300,
      "bandwidth_sharetype": "PER",
      "eip_type": "5_bgp"
    }'
    kubernetes.io/elb.enterpriseID: 00000-00000-000000-00000 # Enterprise Project ID
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN     # Load balancer algorithm
  labels: 
    app.kubernetes.io/component: open-webui
    app.kubernetes.io/instance: kubeai
  name: elb-svc-openwebui
spec: 
  ports: 
  - name: service0 
    port: 8888 # Your external access port
    protocol: TCP 
    targetPort: 8080
  selector: 
    app.kubernetes.io/component: open-webui
    app.kubernetes.io/instance: kubeai
  type: LoadBalancer
